server:
  port: 9097
  session:
    timeout: 38000
    persistent: true

endpoints:
  enabled: false
  shutdown:
    enabled: false
  jmx:
    enabled: false


spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    #    dataSourceClassName: org.gjt.mm.mysql.Driver
    #    url: jdbc:mysql://117.52.98.39:3306/portal_dev?useUnicode=true&characterEncoding=utf-8
    #    username: portal_dev
    #    password: 1234qwer
    #    validationQuery: SELECT 1
    #    testOnBorrow: true
    dataSourceClassName : org.postgresql.Driver
    url: jdbc:postgresql://117.52.98.39:5432/portal_dev2?createDatabaseIfNotExist=true
    username: portal_dev
    password: 1234qwer

  mvc:
    favicon:
      enabled: false

  http:
    multipart:
      maxFileSize: 300MB
      maxRequestSize: 300MB

  mail:
    host: smart.whoismail.net
    port: 25
    username: aworksrpa
    password: 'CloudRPA!1'
    protocol: smtp
    properties:
      mail:
        smtp:
          start-tls-enable: true
          auth: true
          ssl:
            enable: false
        transport:
          protocol: smtps

amazonProperties:
  endpointUrl: https://s3.ap-northeast-2.amazonaws.com
  accessKey: AKIATXFDPE2FYNPJMU42
  #  accessKey: AKIA2A5WUWVQQKDKMA7B
  secretKey: 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
  #  secretKey: Qwz994PGQnit9BfTpt5xYIh6DoTZWMMf+xr+mc+n
  bucketName: awork-aws-test
#  bucketName: a.works


mybatis:
  config: classpath:mybatis-config.xml


logging:
  config: classpath:logback.xml

log4j:
  logger:
    jdbc:
      sqltiming: DEBUG
    package:
      path: TRACE
    java:
      sql:
        Connection: DEBUG
        Statement: DEBUG
        PreparedStatement: DEBUG
        ResultSet: DEBUG
aes:
  pw: poscoict

workcenter:
  url: http://localhost:9090
  clientId: cloudrpa-client1
  clientSecret: 7aKTMjx9qkHHipSg
  grantType: password
  userName: poscoict@poscoict.com
  password: poscoict