server:
  port: 9098
  session:
    timeout: 38000
    persistent: true

endpoints:
  enabled: false
  shutdown:
    enabled: false
  jmx:
    enabled: false


spring:
  profiles:
    active: local

  devtools:
    livereload:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    #    dataSourceClassName: org.gjt.mm.mysql.Driver
    #    url: jdbc:mysql://117.52.98.39:3306/portal_dev?useUnicode=true&characterEncoding=utf-8
    #    username: portal_dev
    #    password: 1234qwer
    #    validationQuery: SELECT 1
    #    testOnBorrow: true
    dataSourceClassName: org.postgresql.Driver
    url: jdbc:postgresql://117.52.98.39:5432/portal_dev2?createDatabaseIfNotExist=true
    username: portal_dev
    password: 1234qwer

  mvc:
    favicon:
      enabled: false

  freemarker:
    cache: false

  http:
    multipart:
      maxFileSize: 150MB
      maxRequestSize: 150MB

  mail:
    host: smtp.gmail.com
    port: 465
    username: kjh@laidback.co.kr
    password: 'wlgns9337'
    protocol: smtp
    properties:
      mail:
        smtp:
          start-tls-enable: true
          auth: true
          ssl:
            enable: true
        transport:
          protocol: smtps

amazonProperties:
  endpointUrl: https://s3.ap-northeast-2.amazonaws.com
  accessKey: AKIAIHWCQI5LHZZLZLBA
  secretKey: 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
  bucketName: awork-aws-test



mybatis:
  config: classpath:mybatis-config.xml


logging:
  config: classpath:logback.xml

log4j:
  logger:
    jdbc:
      sqltiming: DEBUG
    package:
      path: TRACE
    java:
      sql:
        Connection: DEBUG
        Statement: DEBUG
        PreparedStatement: DEBUG
        ResultSet: DEBUG
aes:
  pw: poscoict
jwt:
  privateKey: 'poscoict'
  cookieName: 'poscoToken'
gethost:
  host: localhost